spring.application.name=portfolio-backend
server.port=8080

# Cloud Database Configuration using Environment Variables
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/portfolio_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arkarphonepyae58@gmail.com
spring.mail.password=hqmm xuxz lsdv nonp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true